#!/bin/bash
#
# Copyright (c) 2026, Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# SPDX-License-Identifier: MPL-2.0
#
# Setup development environment for ASAM OSI Utilities
# This script uses native Git hooks - no Python required

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=============================================="
echo "ASAM OSI Utilities - Development Setup"
echo "=============================================="
echo ""

# Check for required C++ tools
echo "Checking required tools..."
echo ""

# Check for clang-format
if command -v clang-format &> /dev/null; then
    echo "✓ clang-format found: $(clang-format --version | head -n1)"
else
    echo "WARNING: clang-format not found (optional, for code formatting)"
    echo "  Install via: apt install clang-format (Debian/Ubuntu)"
    echo "           or: brew install clang-format (macOS)"
fi

# Check for CMake
if command -v cmake &> /dev/null; then
    echo "✓ CMake found: $(cmake --version | head -n1)"
else
    echo "WARNING: CMake not found"
    echo "  Install via: apt install cmake (Debian/Ubuntu)"
    echo "           or: brew install cmake (macOS)"
fi

# Check for Ninja (recommended for compile_commands.json on Windows)
if command -v ninja &> /dev/null; then
    echo "✓ Ninja found: $(ninja --version)"
else
    echo "WARNING: Ninja not found (recommended for clangd on Windows)"
    echo "  Install via: winget install Ninja-build.Ninja (Windows)"
fi


# Install Git hooks
echo ""
echo "Installing Git hooks..."
HOOKS_DIR="$REPO_ROOT/.git/hooks"
mkdir -p "$HOOKS_DIR"

# Create pre-commit hook
cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/sh
# Auto-generated by setup-dev.sh - Native Git pre-commit hook
# Works on Linux, macOS, and Windows (Git Bash)
#
# Usage:
#   .git/hooks/pre-commit                     # Check staged files only (default)
#   .git/hooks/pre-commit --run-all           # Check all C++ files in the project
#   .git/hooks/pre-commit --fix               # Auto-fix staged files (clang-format -i)
#   .git/hooks/pre-commit --run-all --fix     # Auto-fix all C++ files

RUN_ALL=0
FIX=0
for arg in "$@"; do
    if [ "$arg" = "--run-all" ]; then
        RUN_ALL=1
    elif [ "$arg" = "--fix" ]; then
        FIX=1
    fi
done

# Check if VERSION file is staged and sync to other files (only in normal mode)
if [ $RUN_ALL -eq 0 ] && git diff --cached --name-only | grep -q "^VERSION$"; then
    echo "VERSION file changed, syncing to vcpkg.json and Doxyfile.in..."
    VERSION=$(cat VERSION | tr -d '[:space:]')
    
    # Update vcpkg.json
    if [ -f "vcpkg.json" ]; then
        if command -v sed &> /dev/null; then
            sed -i.bak "s/\"version-string\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"version-string\": \"$VERSION\"/" vcpkg.json
            rm -f vcpkg.json.bak 2>/dev/null
            git add vcpkg.json
            echo "  ✓ Updated vcpkg.json"
        fi
    fi
    
    # Update Doxyfile.in
    if [ -f "doc/Doxyfile.in" ]; then
        if command -v sed &> /dev/null; then
            sed -i.bak "s/^PROJECT_NUMBER[[:space:]]*=.*/PROJECT_NUMBER         = $VERSION/" doc/Doxyfile.in
            rm -f doc/Doxyfile.in.bak 2>/dev/null
            git add doc/Doxyfile.in
            echo "  ✓ Updated Doxyfile.in"
        fi
    fi
fi

# Get list of C++ files to check
if [ $RUN_ALL -eq 1 ]; then
    echo "Checking all C++ files..."
    FILES=$(find src include tests examples -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.c" \) 2>/dev/null | grep -v "^lib/")
else
    FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(cpp|h|hpp|c)$" | grep -v "^lib/")
fi

if [ -n "$FILES" ]; then
    if [ $FIX -eq 1 ]; then
        echo "Auto-fixing code formatting..."
    else
        echo "Checking code formatting..."
    fi
    FAILED=0
    for FILE in $FILES; do
        if command -v clang-format &> /dev/null; then
            if [ $FIX -eq 1 ]; then
                clang-format -i "$FILE" 2>/dev/null
                if [ $RUN_ALL -eq 0 ]; then
                    git add "$FILE"
                fi
            else
                if ! clang-format --dry-run --Werror "$FILE" 2>/dev/null; then
                    echo "  ✗ $FILE needs formatting"
                    FAILED=1
                fi
            fi
        fi
    done
    if [ $FIX -eq 1 ]; then
        echo "✓ Code formatting fixed"
    else
        if [ $FAILED -ne 0 ]; then
            echo ""
            echo "Please run: .git/hooks/pre-commit --fix"
            exit 1
        fi
        echo "✓ Code formatting OK"
    fi
else
    if [ $RUN_ALL -eq 1 ]; then
        echo "No C++ files found to check."
    fi
fi

# Run clang-tidy (lint) when available
if command -v clang-tidy &> /dev/null; then
    if [ -f "build/compile_commands.json" ]; then
        COMPILE_DIR="build"
    elif [ -f "build-ninja/compile_commands.json" ]; then
        COMPILE_DIR="build-ninja"
    else
        COMPILE_DIR=""
    fi

    if [ -n "$COMPILE_DIR" ]; then
        if [ $RUN_ALL -eq 1 ]; then
            TIDY_FILES=$(find src include tests examples -type f \( -name "*.cpp" \) 2>/dev/null | grep -v "^lib/")
        else
            TIDY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.cpp$" | grep -v "^lib/")
        fi

        if [ -n "$TIDY_FILES" ]; then
            echo "Running clang-tidy..."
            LINT_FAILED=0
            for FILE in $TIDY_FILES; do
                if ! clang-tidy -p "$COMPILE_DIR" --warnings-as-errors='*' "$FILE"; then
                    LINT_FAILED=1
                fi
            done
            if [ $LINT_FAILED -ne 0 ]; then
                exit 1
            fi
            echo "✓ clang-tidy OK"
        fi
    else
        echo "clang-tidy skipped (no compile_commands.json found). Build once to generate it."
    fi
else
    echo "clang-tidy not found, skipping lint"
fi

exit 0
EOF
chmod +x "$HOOKS_DIR/pre-commit"
echo "✓ Pre-commit hook installed"

# Create commit-msg hook
cat > "$HOOKS_DIR/commit-msg" << 'EOF'
#!/bin/sh
# Auto-generated by setup-dev.sh - Native Git commit-msg hook

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check DCO sign-off
if ! echo "$COMMIT_MSG" | grep -q "^Signed-off-by: "; then
    echo "ERROR: Commit message must include DCO sign-off"
    echo ""
    echo "Add sign-off with: git commit -s -m \"message\""
    echo "Or amend: git commit --amend -s"
    exit 1
fi

# Check conventional commit format (skip merge/revert commits)
FIRST_LINE=$(echo "$COMMIT_MSG" | head -n1)
if ! echo "$FIRST_LINE" | grep -qE "^(Merge|Revert)"; then
    if ! echo "$FIRST_LINE" | grep -qE "^(feat|fix|docs|style|refactor|test|chore|ci|perf|build)(\([a-zA-Z0-9_-]+\))?: .+"; then
        echo "ERROR: Commit message must follow Conventional Commits format"
        echo ""
        echo "Format: <type>(<scope>): <description>"
        echo "Types: feat, fix, docs, style, refactor, test, chore, ci, perf, build"
        echo ""
        echo "Example: feat(mcap): add compression support"
        exit 1
    fi
fi

echo "✓ Commit message OK"
exit 0
EOF
chmod +x "$HOOKS_DIR/commit-msg"
echo "✓ Commit-msg hook installed"

# Check Git configuration for signing
echo ""
echo "=============================================="
echo "Git Configuration for Signed Commits"
echo "=============================================="

# Check for user.name and user.email
GIT_NAME=$(git config --get user.name || echo "")
GIT_EMAIL=$(git config --get user.email || echo "")

if [ -z "$GIT_NAME" ]; then
    echo "WARNING: Git user.name is not set"
    echo "  Run: git config --global user.name \"Your Name\""
else
    echo "✓ Git user.name: $GIT_NAME"
fi

if [ -z "$GIT_EMAIL" ]; then
    echo "WARNING: Git user.email is not set"
    echo "  Run: git config --global user.email \"your.email@example.com\""
else
    echo "✓ Git user.email: $GIT_EMAIL"
fi

# Check for GPG signing configuration
GPG_SIGN=$(git config --get commit.gpgsign || echo "false")
GPG_KEY=$(git config --get user.signingkey || echo "")

echo ""
if [ "$GPG_SIGN" = "true" ]; then
    echo "✓ GPG signing is enabled"
    if [ -n "$GPG_KEY" ]; then
        echo "✓ GPG signing key: $GPG_KEY"
    else
        echo "WARNING: GPG signing is enabled but no key is set"
        echo "  Run: git config --global user.signingkey YOUR_KEY_ID"
    fi
else
    echo "INFO: GPG signing is not enabled"
    echo ""
    echo "To enable GPG signed commits (recommended):"
    echo "  1. Generate a GPG key: gpg --full-generate-key"
    echo "  2. List keys: gpg --list-secret-keys --keyid-format=long"
    echo "  3. Configure Git:"
    echo "     git config --global user.signingkey YOUR_KEY_ID"
    echo "     git config --global commit.gpgsign true"
    echo "  4. Add key to GitHub: https://github.com/settings/keys"
fi

echo ""
echo "=============================================="
echo "Setup Complete!"
echo "=============================================="
echo ""
echo "You can now start developing. Remember:"
echo "  - Sign off commits: git commit -s -m \"message\""
echo "  - GPG sign commits: git commit -S -s -m \"message\""
echo "  - Run format check on all files: .git/hooks/pre-commit --run-all"
