#
# Copyright (c) 2026, Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# SPDX-License-Identifier: MPL-2.0
#
# Setup development environment for ASAM OSI Utilities (Windows PowerShell)
# This script uses native Git hooks - no Python required

Write-Host "=============================================="
Write-Host "ASAM OSI Utilities - Development Setup"
Write-Host "=============================================="
Write-Host ""

# Check for required C++ tools
Write-Host "Checking required tools..."
Write-Host ""

# Check for clang-format
try {
    $clangFormatVersion = clang-format --version 2>&1
    Write-Host "✓ clang-format found: $clangFormatVersion"
}
catch {
    Write-Host "WARNING: clang-format not found (optional, for code formatting)"
    Write-Host "  Install via: winget install LLVM.LLVM"
}

# Check for CMake
try {
    $cmakeVersion = cmake --version 2>&1 | Select-Object -First 1
    Write-Host "✓ CMake found: $cmakeVersion"
}
catch {
    Write-Host "WARNING: CMake not found"
    Write-Host "  Install via: winget install Kitware.CMake"
}

# Check for Ninja (recommended for clangd on Windows)
try {
    $ninjaVersion = ninja --version 2>&1
    Write-Host "✓ Ninja found: $ninjaVersion"
}
catch {
    Write-Host "WARNING: Ninja not found (recommended for clangd on Windows)"
    Write-Host "  Install via: winget install Ninja-build.Ninja"
}


# Install Git hooks
Write-Host ""
Write-Host "Installing Git hooks..."
$hooksDir = Join-Path $PSScriptRoot ".." ".git" "hooks"
$scriptsHooksDir = Join-Path $PSScriptRoot "hooks"

# Create hooks directory if it doesn't exist
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
}

# Create pre-commit hook
$preCommitHook = @'
#!/bin/sh
# Auto-generated by setup-dev.ps1 - Native Git pre-commit hook
# Works on Linux, macOS, and Windows (Git Bash)
#
# Usage:
#   .git/hooks/pre-commit                     # Check staged files only (default)
#   .git/hooks/pre-commit --run-all           # Check all C++ files in the project
#   .git/hooks/pre-commit --fix               # Auto-fix staged files (clang-format -i)
#   .git/hooks/pre-commit --run-all --fix     # Auto-fix all C++ files

RUN_ALL=0
FIX=0
for arg in "$@"; do
    if [ "$arg" = "--run-all" ]; then
        RUN_ALL=1
    elif [ "$arg" = "--fix" ]; then
        FIX=1
    fi
done

# Get list of C++ files to check
if [ $RUN_ALL -eq 1 ]; then
    echo "Checking all C++ files..."
    FILES=$(find src include tests examples -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.c" \) 2>/dev/null | grep -v "^lib/")
else
    FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(cpp|h|hpp|c)$" | grep -v "^lib/")
fi

if [ -n "$FILES" ]; then
    if [ $FIX -eq 1 ]; then
        echo "Auto-fixing code formatting..."
    else
        echo "Checking code formatting..."
    fi
    FAILED=0
    for FILE in $FILES; do
        if command -v clang-format &> /dev/null; then
            if [ $FIX -eq 1 ]; then
                clang-format -i "$FILE" 2>/dev/null
                if [ $RUN_ALL -eq 0 ]; then
                    git add "$FILE"
                fi
            else
                if ! clang-format --dry-run --Werror "$FILE" 2>/dev/null; then
                    echo "  ✗ $FILE needs formatting"
                    FAILED=1
                fi
            fi
        fi
    done
    if [ $FIX -eq 1 ]; then
        echo "✓ Code formatting fixed"
    else
        if [ $FAILED -ne 0 ]; then
            echo ""
            echo "Please run: .git/hooks/pre-commit --fix"
            exit 1
        fi
        echo "✓ Code formatting OK"
    fi
else
    if [ $RUN_ALL -eq 1 ]; then
        echo "No C++ files found to check."
    fi
fi

# Run clang-tidy (lint) when available
if command -v clang-tidy &> /dev/null; then
    if [ -f "build/compile_commands.json" ]; then
        COMPILE_DIR="build"
    elif [ -f "build-ninja/compile_commands.json" ]; then
        COMPILE_DIR="build-ninja"
    else
        COMPILE_DIR=""
    fi

    if [ -n "$COMPILE_DIR" ]; then
        if [ $RUN_ALL -eq 1 ]; then
            TIDY_FILES=$(find src include tests examples -type f \( -name "*.cpp" \) 2>/dev/null | grep -v "^lib/")
        else
            TIDY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.cpp$" | grep -v "^lib/")
        fi

        if [ -n "$TIDY_FILES" ]; then
            echo "Running clang-tidy..."
            LINT_FAILED=0
            for FILE in $TIDY_FILES; do
                if ! clang-tidy -p "$COMPILE_DIR" --warnings-as-errors='*' "$FILE"; then
                    LINT_FAILED=1
                fi
            done
            if [ $LINT_FAILED -ne 0 ]; then
                exit 1
            fi
            echo "✓ clang-tidy OK"
        fi
    else
        echo "clang-tidy skipped (no compile_commands.json found). Build once to generate it."
    fi
else
    echo "clang-tidy not found, skipping lint"
fi

exit 0
'@

$preCommitPath = Join-Path $hooksDir "pre-commit"
$preCommitHook | Out-File -FilePath $preCommitPath -Encoding utf8 -NoNewline
Write-Host "✓ Pre-commit hook installed"

# Create commit-msg hook
$commitMsgHook = @'
#!/bin/sh
# Auto-generated by setup-dev.ps1 - Native Git commit-msg hook

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check DCO sign-off
if ! echo "$COMMIT_MSG" | grep -q "^Signed-off-by: "; then
    echo "ERROR: Commit message must include DCO sign-off"
    echo ""
    echo "Add sign-off with: git commit -s -m \"message\""
    echo "Or amend: git commit --amend -s"
    exit 1
fi

# Check conventional commit format (skip merge/revert commits)
FIRST_LINE=$(echo "$COMMIT_MSG" | head -n1)
if ! echo "$FIRST_LINE" | grep -qE "^(Merge|Revert)"; then
    if ! echo "$FIRST_LINE" | grep -qE "^(feat|fix|docs|style|refactor|test|chore|ci|perf|build)(\([a-zA-Z0-9_-]+\))?: .+"; then
        echo "ERROR: Commit message must follow Conventional Commits format"
        echo ""
        echo "Format: <type>(<scope>): <description>"
        echo "Types: feat, fix, docs, style, refactor, test, chore, ci, perf, build"
        echo ""
        echo "Example: feat(mcap): add compression support"
        exit 1
    fi
fi

echo "✓ Commit message OK"
exit 0
'@

$commitMsgPath = Join-Path $hooksDir "commit-msg"
$commitMsgHook | Out-File -FilePath $commitMsgPath -Encoding utf8 -NoNewline
Write-Host "✓ Commit-msg hook installed"

# Check Git configuration
Write-Host ""
Write-Host "=============================================="
Write-Host "Git Configuration for Signed Commits"
Write-Host "=============================================="

$gitName = git config --get user.name 2>$null
$gitEmail = git config --get user.email 2>$null

if ([string]::IsNullOrEmpty($gitName)) {
    Write-Host "WARNING: Git user.name is not set"
    Write-Host "  Run: git config --global user.name `"Your Name`""
}
else {
    Write-Host "✓ Git user.name: $gitName"
}

if ([string]::IsNullOrEmpty($gitEmail)) {
    Write-Host "WARNING: Git user.email is not set"
    Write-Host "  Run: git config --global user.email `"your.email@example.com`""
}
else {
    Write-Host "✓ Git user.email: $gitEmail"
}

$gpgSign = git config --get commit.gpgsign 2>$null
$gpgKey = git config --get user.signingkey 2>$null

Write-Host ""
if ($gpgSign -eq "true") {
    Write-Host "✓ GPG signing is enabled"
    if (-not [string]::IsNullOrEmpty($gpgKey)) {
        Write-Host "✓ GPG signing key: $gpgKey"
    }
    else {
        Write-Host "WARNING: GPG signing is enabled but no key is set"
        Write-Host "  Run: git config --global user.signingkey YOUR_KEY_ID"
    }
}
else {
    Write-Host "INFO: GPG signing is not enabled"
    Write-Host ""
    Write-Host "To enable GPG signed commits (recommended):"
    Write-Host "  1. Generate a GPG key: gpg --full-generate-key"
    Write-Host "  2. List keys: gpg --list-secret-keys --keyid-format=long"
    Write-Host "  3. Configure Git:"
    Write-Host "     git config --global user.signingkey YOUR_KEY_ID"
    Write-Host "     git config --global commit.gpgsign true"
    Write-Host "  4. Add key to GitHub: https://github.com/settings/keys"
}

Write-Host ""
Write-Host "=============================================="
Write-Host "Setup Complete!"
Write-Host "=============================================="
Write-Host ""
Write-Host "You can now start developing. Remember:"
Write-Host "  - Sign off commits: git commit -s -m `"message`""
Write-Host "  - GPG sign commits: git commit -S -s -m `"message`""
Write-Host "  - Run format check on all files: .git/hooks/pre-commit --run-all"
