#!/bin/bash
#
# SPDX-FileCopyrightText: Copyright (c) 2026, Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# SPDX-License-Identifier: MPL-2.0
#
# Setup development environment for ASAM OSI Utilities
# This script uses native Git hooks - no Python required

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CLANG_FORMAT_RESOLVER="$SCRIPT_DIR/resolve-clang-format.sh"
PINNED_CLANG_FORMAT_MAJOR=18

echo "=============================================="
echo "ASAM OSI Utilities - Development Setup"
echo "=============================================="
echo ""
echo "Note: On Windows, run this script from Git Bash or via: bash scripts/setup-dev.sh"
echo ""

# Check for required C++ tools
echo "Checking required tools..."
echo ""

# Check for clang-format
if CLANG_FORMAT_BIN="$(sh "$CLANG_FORMAT_RESOLVER" 2>/dev/null)"; then
    echo "✓ clang-format found: $("$CLANG_FORMAT_BIN" --version | head -n1)"
else
    echo "WARNING: clang-format ${PINNED_CLANG_FORMAT_MAJOR}.x not found (required for C++ code formatting)"
    echo "  Install via: apt install clang-format-${PINNED_CLANG_FORMAT_MAJOR} (Debian/Ubuntu)"
    echo "           or: brew install llvm@${PINNED_CLANG_FORMAT_MAJOR} (macOS)"
    echo "           or: winget install --id LLVM.LLVM --source winget --version <latest-${PINNED_CLANG_FORMAT_MAJOR}.x> (Windows)"
fi

# Check for CMake
if command -v cmake &> /dev/null; then
    echo "✓ CMake found: $(cmake --version | head -n1)"
else
    echo "WARNING: CMake not found"
    echo "  Install via: apt install cmake (Debian/Ubuntu)"
    echo "           or: brew install cmake (macOS)"
fi

# Check for Ninja (recommended for compile_commands.json on Windows, if using Git Bash)
if command -v ninja &> /dev/null; then
    echo "✓ Ninja found: $(ninja --version)"
else
    echo "WARNING: Ninja not found (recommended for clangd on Windows)"
    echo "  Install via: winget install Ninja-build.Ninja (Windows, for Git Bash users)"
fi

# Check for Python tools (ruff, sphinx)
echo ""
echo "Checking Python tools..."
RUFF_FOUND=0
if command -v ruff &> /dev/null; then
    echo "✓ ruff found: $(ruff --version)"
    RUFF_FOUND=1
elif [ -x "$REPO_ROOT/python/.venv/bin/ruff" ] || [ -x "$REPO_ROOT/python/.venv/Scripts/ruff.exe" ]; then
    echo "✓ ruff found in python/.venv"
    RUFF_FOUND=1
else
    echo "WARNING: ruff not found (for Python lint + format)"
    echo "  Install via: cd python && pip install ruff"
fi

if command -v sphinx-build &> /dev/null; then
    echo "✓ sphinx-build found: $(sphinx-build --version)"
elif [ -x "$REPO_ROOT/python/.venv/bin/sphinx-build" ] || [ -x "$REPO_ROOT/python/.venv/Scripts/sphinx-build.exe" ]; then
    echo "✓ sphinx-build found in python/.venv"
else
    echo "INFO: sphinx-build not found (optional, for --run-docs)"
    echo "  Install via: python3 -m venv python/.venv && python/.venv/bin/pip install -e \"python/[docs]\""
fi


# Install Git hooks
echo ""
echo "Installing Git hooks..."
HOOKS_DIR="$(git -C "$REPO_ROOT" rev-parse --git-path hooks)"
case "$HOOKS_DIR" in
    /* | [A-Za-z]:/*) ;;
    *)
        HOOKS_DIR="$REPO_ROOT/$HOOKS_DIR"
        ;;
esac
mkdir -p "$HOOKS_DIR"

# Create pre-commit hook
cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/sh
# Auto-generated by setup-dev.sh - Native Git pre-commit hook
# Works on Linux, macOS, and Windows (Git Bash)
#
# Multi-language checks: C++ (clang-format, clang-tidy), Python (ruff), Docs (Sphinx)
#
# Usage:
#   $(git rev-parse --git-path hooks)/pre-commit                               # Check staged files (C++ format + Python lint)
#   $(git rev-parse --git-path hooks)/pre-commit --all-files                   # Check all files in the project
#   $(git rev-parse --git-path hooks)/pre-commit --run-tidy                    # Also run clang-tidy (opt-in)
#   $(git rev-parse --git-path hooks)/pre-commit --run-docs                    # Also build documentation (opt-in)
#   $(git rev-parse --git-path hooks)/pre-commit --fix-format                  # Auto-fix C++ formatting
#   $(git rev-parse --git-path hooks)/pre-commit --fix-python                  # Auto-fix Python lint/format
#   $(git rev-parse --git-path hooks)/pre-commit --fix-tidy                    # Auto-fix clang-tidy issues
#   $(git rev-parse --git-path hooks)/pre-commit --skip-tests                  # Skip tests/ in checks
#   $(git rev-parse --git-path hooks)/pre-commit --skip-format                 # Skip C++ clang-format checks
#   $(git rev-parse --git-path hooks)/pre-commit --skip-tidy                   # Skip clang-tidy checks
#   $(git rev-parse --git-path hooks)/pre-commit --skip-python                 # Skip Python ruff checks
#   $(git rev-parse --git-path hooks)/pre-commit --skip-docs                   # Skip documentation build
#   $(git rev-parse --git-path hooks)/pre-commit --all-files --run-tidy --run-docs   # Full check suite
#
# Default behavior (no flags):
#   - C++ formatting via clang-format 18: ON (staged files)
#   - Python lint+format via ruff:     ON (staged files)
#   - C++ linting via clang-tidy:      OFF (use --run-tidy)
#   - Documentation build:             OFF (use --run-docs)

ALL_FILES=0
FIX_FORMAT=0
FIX_TIDY=0
FIX_PYTHON=0
RUN_TIDY=0
RUN_DOCS=0
SKIP_TESTS=0
SKIP_FORMAT=0
SKIP_TIDY=0
SKIP_PYTHON=0
SKIP_DOCS=0
for arg in "$@"; do
    case "$arg" in
        --all-files) ALL_FILES=1 ;;
        --run-tidy) RUN_TIDY=1 ;;
        --run-docs) RUN_DOCS=1 ;;
        --fix-format) FIX_FORMAT=1 ;;
        --fix-tidy) FIX_TIDY=1; RUN_TIDY=1 ;;
        --fix-python) FIX_PYTHON=1 ;;
        --skip-tests) SKIP_TESTS=1 ;;
        --skip-format) SKIP_FORMAT=1 ;;
        --skip-tidy) SKIP_TIDY=1 ;;
        --skip-python) SKIP_PYTHON=1 ;;
        --skip-docs) SKIP_DOCS=1 ;;
    esac
done
if [ $SKIP_TIDY -eq 1 ]; then
    RUN_TIDY=0
fi
if [ $SKIP_DOCS -eq 1 ]; then
    RUN_DOCS=0
fi

RUN_FORMAT=1
if [ $SKIP_FORMAT -eq 1 ]; then
    RUN_FORMAT=0
fi
# If the user explicitly requested clang-tidy, only run formatting when asked.
if [ $RUN_TIDY -eq 1 ] && [ $FIX_FORMAT -eq 0 ]; then
    RUN_FORMAT=0
fi

REPO_ROOT=$(git rev-parse --show-toplevel)
HOOK_PATH="$(git rev-parse --git-path hooks)/pre-commit"
CLANG_FORMAT_RESOLVER="$REPO_ROOT/scripts/resolve-clang-format.sh"

# ===== C++ formatting (clang-format 18) =====

# Determine search roots based on skip flags
if [ $SKIP_TESTS -eq 1 ]; then
    SEARCH_DIRS="cpp/src cpp/include cpp/examples"
    ROOT_REGEX="^cpp/(src|include|examples)/"
else
    SEARCH_DIRS="cpp/src cpp/include cpp/tests cpp/examples"
    ROOT_REGEX="^cpp/(src|include|tests|examples)/"
fi

# Get list of C++ files to check
if [ $RUN_FORMAT -eq 1 ]; then
    if [ $ALL_FILES -eq 1 ]; then
        if [ $SKIP_TESTS -eq 1 ]; then
            echo "Checking all C++ files (excluding tests)..."
        else
            echo "Checking all C++ files..."
        fi
        FILES=$(find $SEARCH_DIRS -type f \( -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" -o -name "*.c++" -o -name "*.h" -o -name "*.hpp" -o -name "*.c" \) 2>/dev/null | grep -v "^submodules/")
    else
        FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "${ROOT_REGEX}.*\\.(cpp|cc|cxx|c\\+\\+|h|hpp|c)$" | grep -v "^submodules/")
    fi

    if [ -n "$FILES" ]; then
        if ! CLANG_FORMAT_BIN="$(sh "$CLANG_FORMAT_RESOLVER")"; then
            sh "$CLANG_FORMAT_RESOLVER" --diagnose || true
            exit 1
        fi
        if [ $FIX_FORMAT -eq 1 ]; then
            echo "Auto-fixing C++ formatting..."
        else
            echo "Checking C++ formatting..."
        fi
        FAILED=0
        for FILE in $FILES; do
            if [ $FIX_FORMAT -eq 1 ]; then
                "$CLANG_FORMAT_BIN" -i "$FILE" 2>/dev/null
                if [ $ALL_FILES -eq 0 ]; then
                    git add "$FILE"
                fi
            else
                if ! "$CLANG_FORMAT_BIN" --dry-run --Werror "$FILE" 2>/dev/null; then
                    echo "  ✗ $FILE needs formatting"
                    FAILED=1
                fi
            fi
        done
        if [ $FIX_FORMAT -eq 1 ]; then
            echo "✓ C++ formatting fixed"
        else
            if [ $FAILED -ne 0 ]; then
                echo ""
                echo "Please run: $HOOK_PATH --fix-format"
                exit 1
            fi
            echo "✓ C++ formatting OK"
        fi
    else
        if [ $ALL_FILES -eq 1 ]; then
            echo "No C++ files found to check."
        fi
    fi
else
    if [ $SKIP_FORMAT -eq 1 ]; then
        echo "Skipping clang-format checks (--skip-format)"
    else
        echo "Skipping clang-format checks (tidy-only run; use --fix-format to include)"
    fi
fi

# ===== C++ linting (clang-tidy) — opt-in =====

if command -v clang-tidy-18 &> /dev/null; then
    CLANG_TIDY_BIN="clang-tidy-18"
elif command -v clang-tidy &> /dev/null; then
    CLANG_TIDY_BIN="clang-tidy"
else
    CLANG_TIDY_BIN=""
fi

if [ $RUN_TIDY -eq 1 ]; then
    if [ -n "$CLANG_TIDY_BIN" ]; then
        if [ -f "build-tests/compile_commands.json" ]; then
            COMPILE_DIR="build-tests"
        elif [ -f "build/compile_commands.json" ]; then
            COMPILE_DIR="build"
        elif [ -f "build-ninja/compile_commands.json" ]; then
            COMPILE_DIR="build-ninja"
        else
            COMPILE_DIR=""
        fi

        if [ -n "$COMPILE_DIR" ]; then
            if [ $ALL_FILES -eq 1 ]; then
                TIDY_FILES=$(find $SEARCH_DIRS -type f \( -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" -o -name "*.c++" \) 2>/dev/null | grep -v "^submodules/")
            else
                TIDY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "${ROOT_REGEX}.*\\.(cpp|cc|cxx|c\\+\\+)$" | grep -v "^submodules/")
            fi

            if [ -n "$TIDY_FILES" ]; then
                if [ $FIX_TIDY -eq 1 ]; then
                    echo "Running clang-tidy (auto-fix)..."
                else
                    echo "Running clang-tidy..."
                fi
                LINT_FAILED=0
                for FILE in $TIDY_FILES; do
                    if [ $FIX_TIDY -eq 1 ]; then
                        if ! "$CLANG_TIDY_BIN" -p "$COMPILE_DIR" --warnings-as-errors='*' --fix --fix-errors "$FILE"; then
                            LINT_FAILED=1
                        fi
                        if [ $ALL_FILES -eq 0 ]; then
                            git add "$FILE"
                        fi
                    else
                        if ! "$CLANG_TIDY_BIN" -p "$COMPILE_DIR" --warnings-as-errors='*' "$FILE"; then
                            LINT_FAILED=1
                        fi
                    fi
                done
                if [ $LINT_FAILED -ne 0 ]; then
                    if [ $FIX_TIDY -eq 0 ]; then
                        echo ""
                        echo "Please run: $HOOK_PATH --fix-tidy"
                    fi
                    exit 1
                fi
                echo "✓ clang-tidy OK"
            fi
        else
            echo "clang-tidy skipped (no compile_commands.json found). Build once to generate it."
        fi
    else
        echo "clang-tidy not found, skipping lint"
    fi
else
    if [ $SKIP_TIDY -eq 1 ]; then
        echo "Skipping clang-tidy checks (--skip-tidy)"
    else
        echo "Skipping clang-tidy checks (disabled by default; use --run-tidy or --fix-tidy)"
    fi
fi

# ===== Python lint + format (ruff) =====

if [ $SKIP_PYTHON -eq 0 ]; then
    # Find ruff in common locations
    RUFF_BIN=""
    if command -v ruff &> /dev/null; then
        RUFF_BIN="ruff"
    elif [ -x "python/.venv/bin/ruff" ]; then
        RUFF_BIN="python/.venv/bin/ruff"
    elif [ -x "python/.venv/Scripts/ruff.exe" ]; then
        RUFF_BIN="python/.venv/Scripts/ruff.exe"
    fi

    if [ -n "$RUFF_BIN" ]; then
        PY_DIRS="python/osi_utilities python/tests"

        if [ $ALL_FILES -eq 1 ]; then
            PY_FILES=$(find $PY_DIRS -type f -name "*.py" 2>/dev/null)
        else
            PY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "^python/.*\\.py$")
        fi

        if [ -n "$PY_FILES" ]; then
            if [ $FIX_PYTHON -eq 1 ]; then
                echo "Auto-fixing Python lint + format..."
                "$RUFF_BIN" check --fix $PY_FILES 2>/dev/null
                "$RUFF_BIN" format $PY_FILES 2>/dev/null
                if [ $ALL_FILES -eq 0 ]; then
                    echo "$PY_FILES" | xargs git add
                fi
                echo "✓ Python lint + format fixed"
            else
                echo "Checking Python lint + format..."
                PY_FAILED=0
                if ! "$RUFF_BIN" check $PY_FILES 2>/dev/null; then
                    PY_FAILED=1
                fi
                if ! "$RUFF_BIN" format --check $PY_FILES 2>/dev/null; then
                    PY_FAILED=1
                fi
                if [ $PY_FAILED -ne 0 ]; then
                    echo ""
                    echo "Please run: .git/hooks/pre-commit --fix-python"
                    exit 1
                fi
                echo "✓ Python lint + format OK"
            fi
        else
            if [ $ALL_FILES -eq 1 ]; then
                echo "No Python files found to check."
            fi
        fi
    else
        echo "ruff not found, skipping Python checks (install: pip install ruff)"
    fi
else
    echo "Skipping Python checks (--skip-python)"
fi

# ===== Documentation build (Doxygen + Sphinx) — opt-in =====

if [ $RUN_DOCS -eq 1 ]; then
    echo "Building documentation..."
    DOCS_FAILED=0

    # Find sphinx-build
    SPHINX_BIN=""
    if command -v sphinx-build &> /dev/null; then
        SPHINX_BIN="sphinx-build"
    elif [ -x "python/.venv/bin/sphinx-build" ]; then
        SPHINX_BIN="python/.venv/bin/sphinx-build"
    elif [ -x "python/.venv/Scripts/sphinx-build.exe" ]; then
        SPHINX_BIN="python/.venv/Scripts/sphinx-build.exe"
    fi

    if [ -n "$SPHINX_BIN" ]; then
        # Run Doxygen first if available (generates XML for Breathe)
        if command -v doxygen &> /dev/null; then
            if [ -f "doc/Doxyfile.in" ]; then
                # Use configured Doxyfile from build dir if available, otherwise configure inline
                DOXYFILE=""
                for BUILD_DIR in build-vcpkg build build-ninja; do
                    if [ -f "$BUILD_DIR/doc/Doxyfile" ]; then
                        DOXYFILE="$BUILD_DIR/doc/Doxyfile"
                        break
                    fi
                done
                if [ -n "$DOXYFILE" ]; then
                    echo "  Running Doxygen (XML generation)..."
                    if ! doxygen "$DOXYFILE" > /dev/null 2>&1; then
                        echo "  ✗ Doxygen failed"
                        DOCS_FAILED=1
                    else
                        echo "  ✓ Doxygen XML OK"
                    fi
                else
                    echo "  Doxygen skipped (no configured Doxyfile found; run cmake first)"
                fi
            fi
        else
            echo "  Doxygen not found, skipping C++ XML generation"
        fi

        # Run Sphinx build
        echo "  Running Sphinx build..."
        if ! "$SPHINX_BIN" -b html --keep-going -q doc doc/_build/html 2>&1; then
            echo "  ✗ Sphinx build failed"
            DOCS_FAILED=1
        else
            echo "  ✓ Sphinx build OK"
        fi

        # Clean up local build artifacts
        rm -rf doc/_build

        if [ $DOCS_FAILED -ne 0 ]; then
            echo ""
            echo "Documentation build failed. Fix the issues above before committing."
            exit 1
        fi
        echo "✓ Documentation OK"
    else
        echo "sphinx-build not found, skipping docs check (install: python/.venv/bin/pip install -e \"python/[docs]\")"
    fi
else
    if [ $SKIP_DOCS -eq 1 ]; then
        echo "Skipping documentation build (--skip-docs)"
    else
        echo "Skipping documentation build (disabled by default; use --run-docs)"
    fi
fi

exit 0
EOF
chmod +x "$HOOKS_DIR/pre-commit"
echo "✓ Pre-commit hook installed"

# Create commit-msg hook
cat > "$HOOKS_DIR/commit-msg" << 'EOF'
#!/bin/sh
# Auto-generated by setup-dev.sh - Native Git commit-msg hook

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check DCO sign-off
if ! echo "$COMMIT_MSG" | grep -q "^Signed-off-by: "; then
    echo "ERROR: Commit message must include DCO sign-off"
    echo ""
    echo "Add sign-off with: git commit -s -m \"message\""
    echo "Or amend: git commit --amend -s"
    exit 1
fi

# Check conventional commit format (skip merge/revert commits)
FIRST_LINE=$(echo "$COMMIT_MSG" | head -n1)
if ! echo "$FIRST_LINE" | grep -qE "^(Merge|Revert)"; then
    if ! echo "$FIRST_LINE" | grep -qE "^(feat|fix|docs|style|refactor|test|chore|ci|perf|build)(\([a-zA-Z0-9_-]+\))?: .+"; then
        echo "ERROR: Commit message must follow Conventional Commits format"
        echo ""
        echo "Format: <type>(<scope>): <description>"
        echo "Types: feat, fix, docs, style, refactor, test, chore, ci, perf, build"
        echo ""
        echo "Example: feat(mcap): add compression support"
        exit 1
    fi
fi

echo "✓ Commit message OK"
exit 0
EOF
chmod +x "$HOOKS_DIR/commit-msg"
echo "✓ Commit-msg hook installed"

# Check Git configuration for signing
echo ""
echo "=============================================="
echo "Git Configuration for Signed Commits"
echo "=============================================="

# Check for user.name and user.email
GIT_NAME=$(git config --get user.name || echo "")
GIT_EMAIL=$(git config --get user.email || echo "")

if [ -z "$GIT_NAME" ]; then
    echo "WARNING: Git user.name is not set"
    echo "  Run: git config --global user.name \"Your Name\""
else
    echo "✓ Git user.name: $GIT_NAME"
fi

if [ -z "$GIT_EMAIL" ]; then
    echo "WARNING: Git user.email is not set"
    echo "  Run: git config --global user.email \"your.email@example.com\""
else
    echo "✓ Git user.email: $GIT_EMAIL"
fi

# Check for GPG signing configuration
GPG_SIGN=$(git config --get commit.gpgsign || echo "false")
GPG_KEY=$(git config --get user.signingkey || echo "")

echo ""
if [ "$GPG_SIGN" = "true" ]; then
    echo "✓ GPG signing is enabled"
    if [ -n "$GPG_KEY" ]; then
        echo "✓ GPG signing key: $GPG_KEY"
    else
        echo "WARNING: GPG signing is enabled but no key is set"
        echo "  Run: git config --global user.signingkey YOUR_KEY_ID"
    fi
else
    echo "INFO: GPG signing is not enabled"
    echo ""
    echo "To enable GPG signed commits (recommended):"
    echo "  1. Generate a GPG key: gpg --full-generate-key"
    echo "  2. List keys: gpg --list-secret-keys --keyid-format=long"
    echo "  3. Configure Git:"
    echo "     git config --global user.signingkey YOUR_KEY_ID"
    echo "     git config --global commit.gpgsign true"
    echo "  4. Add key to GitHub: https://github.com/settings/keys"
fi

echo ""
echo "=============================================="
echo "Setup Complete!"
echo "=============================================="
echo ""
echo "You can now start developing. Remember:"
echo "  - Sign off commits: git commit -s -m \"message\""
echo "  - GPG sign commits: git commit -S -s -m \"message\""
echo ""
echo "  Pre-commit checks (C++ and Python):"
echo "  - Run on all files:    .git/hooks/pre-commit --all-files"
echo "  - Auto-fix C++ format: .git/hooks/pre-commit --fix-format"
echo "  - Auto-fix Python:     .git/hooks/pre-commit --fix-python"
echo "  - Run clang-tidy:      .git/hooks/pre-commit --run-tidy"
echo "  - Build docs:          .git/hooks/pre-commit --run-docs"
echo "  - Full suite:          .git/hooks/pre-commit --all-files --run-tidy --run-docs"
echo "  - Note: --run-tidy/--fix-tidy skips clang-format unless --fix-format is also set"
